# Generated by Django 3.1.6 on 2021-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(default='London', max_length=60),
        ),
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(default='London', max_length=60),
        ),
    ]
